update git scripts to use worktree
https://twitter.com/SmileyKeith/status/1337462155008823298

diff --git a/scripts/git-newpr b/scripts/git-newpr
--- a/scripts/git-newpr
+++ b/scripts/git-newpr
@@ -1,27 +1,60 @@
 #!/bin/bash
 
 set -euo pipefail
+set -x
 
-readonly pr_commit="${1:-core-dev}"
-
-# Autogenerate a branch name based on the commit subject.
-readonly branch_name="$(git show --no-patch --format="%f" "$pr_commit")"
-
-# Create the new branch and switch to it.
-git branch --no-track "$branch_name" origin/core-dev
-git switch "$branch_name"
-
-# Cherry pick the desired commit.
-if ! git cherry-pick "$pr_commit"; then
-    git cherry-pick --abort
-    git switch core-dev
-    exit 1
+readonly commit_arg="${1:-HEAD}"
+if [[ $# -gt 0 ]]; then
+  shift
 fi
 
-# Create a new remote branch by the same name.
-git -c push.default=current push
+readonly commit="$(git rev-parse "$commit_arg")"
+readonly branch_name="$(git show --no-patch --format=%f "$commit" | tr '[:upper:]' '[:lower:]')"
 
-open "https://gitlab.com/fastr/mono/merge_requests/new?merge_request[source_branch]=$branch_name"
+if git show-ref --verify --quiet refs/heads/"$branch_name"; then
+  echo "error: branch named '$branch_name' already exists" >&2
+  exit 1
+fi
 
-# Go back to core-dev branch.
-git switch core-dev
+git branch --no-track "$branch_name" "@{upstream}"
+
+git worktree prune
+readonly worktree_name=$(git rev-parse --show-toplevel | md5)
+readonly worktree_dir="/tmp/$worktree_name"
+# If the OS cleaned the directory in the /tmp dir, it maybe exist but be empty
+rmdir "$worktree_dir" 2>/dev/null || true
+if [[ ! -d "$worktree_dir" ]]; then
+  git worktree add "$worktree_dir" "$branch_name"
+else
+  if ! git -C "$worktree_dir" switch "$branch_name"; then
+    # TODO: should this be -D?
+    git branch -d "$branch_name"
+    exit 1
+  fi
+fi
+
+_checkout_empty() {
+  git -C "$worktree_dir" switch -C "empty-$worktree_name" --quiet
+}
+
+if ! git -C "$worktree_dir" cherry-pick "$commit"; then
+  if git -C "$worktree_dir" mergetool; then
+    git -C "$worktree_dir" -c core.editor=true cherry-pick --continue
+  else
+    # TODO: should this be -D?
+    git -C "$worktree_dir" cherry-pick --abort
+    _checkout_empty
+    git branch -d "$branch_name"
+    exit 1
+  fi
+fi
+
+if git -C "$worktree_dir" push --quiet --set-upstream origin "$branch_name"; then
+  open "https://gitlab.com/fastr/mono/merge_requests/new?merge_request[source_branch]=$branch_name"
+else
+  echo "error: failed to create remote branch" >&2
+  _checkout_empty
+  git branch -d "$branch_name"
+fi
+
+_checkout_empty
diff --git a/scripts/git-updatepr b/scripts/git-updatepr
--- a/scripts/git-updatepr
+++ b/scripts/git-updatepr
@@ -1,37 +1,86 @@
 #!/bin/bash
 
 set -euo pipefail
+set -x
 
-if [[ $# -ne 1 ]]; then
-    echo "usage: $0 <pr-commit>" 2>&1
-    exit
+if [[ $# -lt 1 ]]; then
+  echo "usage: $0 <new_sha> [<sha_to_update>]" >&2
+  exit 1
 fi
 
-readonly pr_commit=$1
+readonly commit_to_update=$1
+readonly new_refspec=$(git rev-parse "${2:-HEAD}")
+readonly base_refspec=$(git rev-parse HEAD)
 
-readonly branch_name="$(git show --no-patch --format="%f" "$pr_commit")"
+if ! git cat-file -e "$commit_to_update" 2> /dev/null; then
+  echo "error: invalid commit sha: '$commit_to_update'" >&2
+  exit 1
+fi
 
-git switch "$branch_name"
+readonly branch_name="ks/$(git show --no-patch --format=%f "$commit_to_update" | tr '[:upper:]' '[:lower:]')"
+if ! git show-ref --verify --quiet refs/heads/"$branch_name"; then
+  echo "error: branch '$branch_name' doesn't exist" >&2
+  exit 1
+fi
 
-# Cherrypick the latest commit to the PR branch.
-if ! git cherry-pick core-dev; then
-    git cherry-pick --abort
-    git switch core-dev
+git worktree prune
+readonly worktree_name=$(git rev-parse --show-toplevel | md5)
+readonly worktree_dir="/tmp/$worktree_name"
+# If the OS cleaned the directory in the /tmp dir, it maybe exist but be empty
+rmdir "$worktree_dir" 2>/dev/null || true
+if [[ ! -d "$worktree_dir" ]]; then
+  git worktree add "$worktree_dir" "$branch_name"
+else
+  git -C "$worktree_dir" switch "$branch_name"
+fi
+
+_checkout_empty() {
+  git -C "$worktree_dir" switch -C "empty-$worktree_name" --quiet
+}
+
+_ask() {
+  read -p "$1" -n 1 -r
+  if [[ "$REPLY" =~ ^[Yy]$ ]]; then
+    echo "y"
+  elif [[ "$REPLY" =~ ^[Nn]$ ]]; then
+    echo "n"
+  else
+    echo >&2
+    _ask "$1"
+  fi
+}
+
+branch_with_remote=$(git -C "$worktree_dir" rev-parse --abbrev-ref --symbolic-full-name "@{upstream}")
+remote_name="${branch_with_remote%%/*}"
+remote_branch_name="${branch_with_remote#*/}"
+
+git -C "$worktree_dir" fetch "$remote_name" "$remote_branch_name"
+if ! git -C "$worktree_dir" diff --quiet "HEAD...@{upstream}"; then
+  answer=$(_ask "warning: upstream has new commits, would you like to pull those (or abort)? (y/n) ")
+  if [[ "$answer" == y ]]; then
+    git -C "$worktree_dir" pull
+  else
+    echo "warning: not updating PR, checkout '$branch_name', pull and try again" >&2
+    _checkout_empty
     exit 1
+  fi
 fi
 
-# Push the updated branch.
-git push origin "$branch_name"
+if ! git -C "$worktree_dir" cherry-pick "$new_refspec^..$base_refspec"; then
+  if git -C "$worktree_dir" mergetool; then
+    git -C "$worktree_dir" cherry-pick --continue
+  else
+    git -C "$worktree_dir" cherry-pick --abort
+    _checkout_empty
+    # TODO what do i do? i think we have to reset branch state? maybe just abort cherry pick?
+    exit 1
+  fi
+fi
 
-# Go back to core-dev.
-git switch core-dev
+git -C "$worktree_dir" push --quiet || echo "warning: failed to push '$branch_name'" >&2
 
-# This allows for scripted (non-interactive) use of interactive rebase.
-export GIT_SEQUENCE_EDITOR=/usr/bin/true
+export GIT_SEQUENCE_EDITOR=true
 
-# In two steps, squash the latest commit into its PR commit.
-# 1. Mark the commit as a fixup
-git commit --amend --fixup="$pr_commit"
-# 2. Use the autosquash feature of interactive rebase to perform the squash.
-git rebase --interactive --autosquash "${pr_commit}^"
-
+git rebase --interactive --exec "git commit --amend --fixup '$commit_to_update'" "$new_refspec"^
+git rebase --interactive --autosquash "$commit_to_update"^
+_checkout_empty
