Update git-pile

diff --git a/scripts/git-updatepr b/scripts/git-updatepr
--- a/scripts/git-updatepr
+++ b/scripts/git-updatepr
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 set -euo pipefail
 
@@ -7,44 +7,48 @@ if [[ -n "${GIT_PILE_VERBOSE:-}" ]]; then
 fi
 
 if [[ $# -lt 1 ]]; then
-  echo "usage: $0 <new_sha> [--squash] [-s] [<sha_to_update>]" >&2
+  echo "usage: $0 <new_sha> [--squash] [<sha_to_update>]" >&2
   exit 1
 fi
 
 export GIT_SEQUENCE_EDITOR=true
 
 readonly commit_to_update=$1
-squash=false
-if [[ "${2:-}" == --squash ]]; then
-  squash=true
-  shift
-fi
-signoff=false
-if [[ "${2:-}" == -s ]]; then
-  signoff=true
-  shift
-fi
+shift
 
-readonly new_refspec=$(git rev-parse "${2:-HEAD}")
-readonly base_refspec=$(git rev-parse HEAD)
+squash=false
+for arg in "$@"
+do
+  case "$arg" in
+    --squash)
+      squash=true
+      shift
+      ;;
+    *)
+      ;;
+  esac
+done
+
+# TODO: I think this is broken-ish as it includes all commits in between the PR sha and the one you're passing to update, which might be unexpected
+new_refspec=$(git rev-parse "${1:-HEAD}")
+base_refspec=$(git rev-parse HEAD)
 
 if ! git cat-file -e "$commit_to_update" 2> /dev/null; then
   echo "error: invalid commit sha: '$commit_to_update'" >&2
   exit 1
 fi
 
-readonly branch_name="${GIT_PILE_PREFIX:-}$(git show --no-patch --format=%f "$commit_to_update" | tr '[:upper:]' '[:lower:]')"
+branch_name="$(git pilebranchname "$commit_to_update")"
 if ! git show-ref --quiet "$branch_name"; then
   echo "error: branch '$branch_name' doesn't exist" >&2
   exit 1
 fi
 
-worktree_name=$(git roothash)
-readonly worktree_dir="$HOME/.cache/git-pile/$worktree_name"
+worktree_dir="$(git pileworktreepath)"
 if [[ ! -d "$worktree_dir" ]]; then
-  git worktree add -f "$worktree_dir" "$branch_name"
+  git worktree add --quiet --force "$worktree_dir" "$branch_name"
 else
-  git -C "$worktree_dir" switch "$branch_name"
+  git -C "$worktree_dir" switch --quiet "$branch_name"
 fi
 
 _detach_branch() {
@@ -69,7 +73,7 @@ branch_with_remote=$(git -C "$worktree_dir" rev-parse --abbrev-ref --symbolic-fu
 remote_name="${branch_with_remote%%/*}"
 remote_branch_name="${branch_with_remote#*/}"
 
-git -C "$worktree_dir" fetch "$remote_name" "$remote_branch_name"
+git -C "$worktree_dir" fetch --quiet "$remote_name" "$remote_branch_name"
 if ! git -C "$worktree_dir" diff --quiet "HEAD...@{upstream}"; then
   git -C "$worktree_dir" diff "HEAD...@{upstream}"
   answer=$(_ask "warning: upstream has new commits, would you like to pull those (or abort)? (y/n) ")
@@ -81,28 +85,29 @@ if ! git -C "$worktree_dir" diff --quiet "HEAD...@{upstream}"; then
   fi
 fi
 
-if ! git -C "$worktree_dir" cherry-pick "$new_refspec^..$base_refspec"; then
+output_file=$(mktemp)
+if ! git -C "$worktree_dir" cherry-pick "$new_refspec^..$base_refspec" >"$output_file" 2>&1; then
+  cat "$output_file" >&2
   # TODO if you exit in vim with :cq, it asks you if it was successful, i think if you hit yes it will continue even if it's not?
   if git -C "$worktree_dir" mergetool; then
-    git -C "$worktree_dir" -c core.editor=true cherry-pick --continue
+    if ! git -C "$worktree_dir" -c core.editor=true cherry-pick --continue; then
+      git -C "$worktree_dir" cherry-pick --abort
+      echo "error: failed to cherry pick anything, was the commit you're adding empty on this branch?" >&2
+      exit 1
+    fi
   else
     git -C "$worktree_dir" cherry-pick --abort
-    # TODO what do i do? i think we have to reset branch state? maybe just abort cherry pick?
     exit 1
   fi
 fi
 
 if [[ "$squash" == true ]]; then
-  if [[ "$signoff" == true ]]; then
-    git -C "$worktree_dir" commit -s --amend --fixup=HEAD~
-  else
-    git -C "$worktree_dir" commit --amend --fixup=HEAD~
-  fi
-  git -C "$worktree_dir" rebase --interactive --autosquash HEAD~2
+  git -C "$worktree_dir" commit --quiet --signoff --no-verify --amend --fixup=HEAD~
+  git -C "$worktree_dir" rebase --quiet --interactive --autosquash HEAD~2
   git -C "$worktree_dir" push --force-with-lease --quiet || echo "warning: failed to force push '$branch_name'" >&2
 else
   git -C "$worktree_dir" push --quiet || echo "warning: failed to push '$branch_name'" >&2
 fi
 
-git rebase --interactive --exec "git commit --amend --fixup '$commit_to_update'" "$new_refspec"^
-git rebase --interactive --autosquash "$commit_to_update"^
+git rebase --quiet --interactive --autostash --exec "git commit --signoff --no-verify --amend --fixup '$commit_to_update'" "$new_refspec"^
+git rebase --quiet --interactive --autostash --autosquash "$commit_to_update"^
